GET http://localhost:3002/items

###
GET http://localhost:3002/items/2

###
GET http://localhost:3002/items/4

###
DELETE http://localhost:3002/items/3

###
POST http://localhost:3002/items
Content-Type: application/json

{
    "name": "Migue",
    "number": "+5493515912166"
}

###
POST http://localhost:3002/items
Content-Type: application/json

{
    
}